[programs.devnet]
staking_program = "6J239Qk8gMNpLKJ6Qd7AckKD4cmv21NzPc8vzMfr6q2o"

[registry]
url = "https://anchor.projectserum.com"

[provider]

cluster = "devnet"
#cluster = "http://127.0.0.1:8899"
#wallet = "/home/gitpod/.config/solana/id.json"
wallet = "./test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
